name: Build and Test - Pixi

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build VRS on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, macos-latest, macos-14] # macos-14 is macSilicon
    steps:
      - name : Setup repo
        uses: actions/checkout@v2

      - name : Setup pixi
        uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: v0.13.0
          cache: false

      - name: Build
        run: pixi run build

      - name: Test
        run: pixi run test